name: Go  # The name of the workflow that will appear on Github

on:
  push:
    branches: [ master, v2 ]
  pull_request:
    branches: [ master, v2 ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: [1.20.7]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      run: go install

    - name: Install goveralls
      run: go install github.com/mattn/goveralls@latest
    
    - name: Run Unit tests
      run: |
        go test -race -covermode atomic -coverprofile=covprofile ./...

    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=covprofile -service=github
